const randomNumber = (max: number): number => {
  return Math.floor(Math.random() * max)
}

export const pickPhrase = (): string => {
  const phrasesArray = [
    'The difference between ordinary and extraordinary is that little extra. --Jimmy Johnson',
    'If you cannot do great things, do small things in a great way. --Napoleon Hill',
    'Tough times never last, but tough people do. --Robert Schuller',
    `Don't worry about failures; worry about the chances you miss when you don't even try. --Jack Canfield`,
    'Be humble. Be hungry. And always be the hardest worked in the room. --The Rock',
    'It does not matter how slowly you go as long as you do not stop. --Confucius',
    'Your dreams don’t have to be lofty; they just have to be lived.--Kelly Bouchard',
    'Taking care of yourself makes you stronger for everyone in your life … including you.--Kelly Rudolph',
    'Laugh at yourself. It tones your facial muscles and attitude.-- Kelly Rudolph',
    'Always remember you are braver than you believe, stronger than you seem, smarter than you think and twice as beautiful as you’ve ever imagined. --Dr. Seuss',
    'The secret of getting ahead is getting started. --Mark Twain',
    'All our dreams can come true, if we have the courage to pursue them. --Walt Disney',
    'I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life and that is why I succeed. --Michael Jordan',
    'Don’t limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. --Mary Kay Ash',
    'The best time to plant a tree was 20 years ago. The second best time is now. --Chinese Proverb',
    'It’s hard to beat a person who never gives up. --Babe Ruth',
    'If people are doubting how far you can go, go so far that you can’t hear them anymore. --Michele Ruiz',
    'We need to accept that we won’t always make the right decisions, that we’ll screw up royally sometimes – understanding that failure is not the opposite of success, it’s part of success. --Arianna Huffingto',
    'Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE. --Joss Whedon',
    'You’ve gotta dance like there’s nobody watching, love like you’ll never be hurt, sing like there’s nobody listening, and live like it’s heaven on earth. --William W. Purkey',
    'Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten. --Neil Gaiman',
    'Everything you can imagine is real. --Pablo Picasso',
    'Do one thing every day that scares you. --Eleanor Roosevelt And let that be today. --From the dev who wrote this with lots of help',
    'Smart people learn from everything and everyone, average people from their experiences, stupid people already have all the answers. --Socrates',
    'Happiness is not something ready made. It comes from your own actions. -- Dalai Lama XIV',
    'The same boiling water that softens the potato hardens the egg. It’s what you’re made of. Not the circumstances. --Unknown',
    'If we have the attitude that it’s going to be a great day it usually is. --Catherine Pulsifier',
    'You can either experience the pain of discipline or the pain of regret. The choice is yours. --Unknown // This one hit home --the beginner dev',
    'Impossible is just an opinion. --Paulo Coelho',
    'Your passion is waiting for your courage to catch up. --Isabelle Lafleche',
    'People who wonder if the glass is half empty or full miss the point. The glass is refillable. --Unknown',
    'One day or day one. You decide. --Unknown',
    `All Motivation Mondays need are a little more coffee and a lot more mascara. --Unknown // The goal should be excited for Monday, but I'll settle for this --I wrote this on a friday evening`,
    'Things may come to those who wait, but only the things left by those who hustle. --Unknown',
    'Invest in your dreams. Grind now. Shine later. --Unknown',
    'We are what we repeatedly do. Excellence, then, is not an act, but a habit. --Aristotle',
    'If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. --Sheryl Sandberg',
    'I always did something I was a little not ready to do. I think that’s how you grow. When there’s that moment of ‘Wow, I’m not really sure I can do this,’ and you push through those moments, that’s when you have a breakthrough. --Marissa Mayer',
    'There is nothing more truly artistic than to love people. --Vincent Van Gogh',
    'If you hear a voice within you say "you cannot paint," then by all means paint and that voice will be silenced. --Vincent Van Gogh',
    'Great things are not done by impulse, but by a series of small things brought together. --Vincent Van Gogh',
    'How wonderful it is that nobody need wait a single moment before starting to improve the world. --Anne Frank',
    'Very often, a change of self is needed more than a change of scene. --A.C. Benson',
    'It’s not the load that breaks you down, it’s the way you carry it. --Lou Holtz // You got this --your awesome dev',
    'If you believe it’ll work out, you’ll see opportunities. If you don’t believe it’ll work out, you’ll see obstacles. --Wayne Dyer',
    'I now tried a new hypothesis: It was possible that I was more in charge of my happiness than I was allowing myself to be. --Michelle Obama',
    'In a gentle way, you can shake the world. --Mahatma Gandhi',
    'If opportunity doesn’t knock, build a door. --Kurt Cobain',
    'Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. --Roy T. Bennett',
    'Don’t say you don’t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresa, Leonardo Da Vinci, Thomas Jefferson, and Albert Einstein. --H. Jackson Brown Jr.',
    'Hard work beats talent when talent doesn’t work hard. --Tim Notke',
    'Opportunity is missed by most people because it is dressed in overalls and looks like work. --Thomas Edison',
    'The only difference between ordinary and extraordinary is that little extra. --Jimmy Johnson',
    'Unsuccessful people make their decisions based on their current situations. Successful people make their decisions based on where they want to be. --Benjamin Hardy',
    'Work hard for what you want because it won’t come to you without a fight. You have to be strong and courageous and know that you can do anything you put your mind to. If somebody puts you down or criticizes you, just keep on believing in yourself and turn it into something positive. --Leah LaBelle',
    'Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway. --Earl Nightingale',
    'If you work on something a little bit every day, you end up with something that is massive. --Kenneth Goldsmith',
    'The big secret in life is that there is no secret. Whatever your goal, you can get there if you’re willing to work. --Oprah Winfrey',
    'If you cannot do great things, do small things in a great way. --Napoleon Hill',
    'At any given moment you have the power to say: this is not how the story is going to end. --Unknown',
    'you can’t connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future. You have to trust in something — your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life --Steve Jobs',
    'You’ve got to find what you love. And that is as true for your work as it is for your lovers. Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. As with all matters of the heart, you’ll know when you find it. And, like any great relationship, it just gets better and better as the years roll on. So keep looking until you find it. Don’t settle. --Steve Jobs',
    'I read a quote that went something like: “If you live each day as if it was your last, someday you’ll most certainly be right.” It made an impression on me, and since then, for the past 33 years, I have looked in the mirror every morning and asked myself: “If today were the last day of my life, would I want to do what I am about to do today?” And whenever the answer has been “No” for too many days in a row, I know I need to change something. --Steve Jobs',
    'Sometimes when you’re in a dark place you think you’ve been buried but you’ve actually been planted. --Christine Caine',
    'Whenever you find yourself doubting how far you can go, just remember how far you have come. --Unknown',
    'Don’t quit yet, the worst moments are usually followed by the most beautiful silver linings. You have to stay strong, remember to keep your head up and remain hopeful. --Unknown',
    'Go the extra mile. It’s never crowded there. --Dr. Wayne D. Dyer',
    'Would you like me to give you a formula for success? It’s quite simple, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure or you can learn from it, so go ahead and make mistakes. Make all you can. Because remember that’s where you will find success. --Thomas J. Watson',
    'To be a champion, I think you have to see the big picture. It’s not about winning and losing; it’s about every day hard work and about thriving on a challenge. It’s about embracing the pain that you’ll experience at the end of a race and not being afraid. I think people think too hard and get afraid of a certain challenge. --Summer Sanders',
    'I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion. --Muhammad Ali',
    'If you obey all the rules, you miss all the fun. --Katharine Hepburn',
    'Never regret anything that made you smile. --Mark Twain',
    'I never lose. Either I win or learn. --Nelson Mandela',
    'Today is your opportunity to build the tomorrow you want. --Ken Poirot',
    'Focus on being productive instead of busy. --Tim Ferriss',
    'You don’t need to see the whole staircase, just take the first step. --Martin Luther King Jr.',
    'When someone says you can’t do it, do it twice and take pictures. --Unknown',
    'Don’t Quit',
    'Nothing can dim the light that shines from within. --Maya Angelou',
    'If you don’t get out of the box you’ve been raised in, you won’t understand how much bigger the world is.” – Angelina Jolie',
    `Reminder, take a you day if you need it --thanks from the dev you're still subscribed to.`,
    'I can and I will. Watch me. --Carrie Green',
    'Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it. --The Lion King',
    'Doubt is a killer. You just have to know who you are and what you stand for. --Jennifer Lopez',
    'The world is changed by your example, not by your opinion. --Paulo Coelho',
    'If you don’t build your dream, someone else will hire you to help them build theirs. --Dhirubhai Ambani',
    'Be a fruitloop in a world of Cheerios. --Unknown',
    'You don’t have to be perfect to be amazing. --Unknown',
    'Always be careful when you follow the masses. Sometimes the m is silent. --Unknown',
    'If you think you’re too small to make a difference, try sleeping with a mosquito. --Dalai Lama',
    'If at first you don’t succeed, then skydiving isn’t for you. --Steven Wright',
    'A diamond is merely a lump of coal that did well under pressure. --Unknown',
    'Remember, you have been criticizing yourself for years and it hasn’t worked. Try approving of yourself and see what happens. --Louise L Hay',
    'If today you are a little bit better than you were yesterday, then that’s enough. --David A. Bednar',
    'Change is painful, but nothing is as painful as staying stuck somewhere you don’t belong. --Mandy Hale',
    'How to stop time: kiss. How to travel in time: read. How to escape time: music. How to feel time: write. How to release time: breathe. --Matt Haig',
    'Think like a Queen. A Queen is not afraid to fail. Failure is another stepping stone to greatness. --Oprah',
    'Why do we grieve failures longer than we celebrate wins? --Komal Kapoor',
    'Whenever you feel like a failure, just remember that even Coca Cola only sold 25 bottles their first year.',
    'Everything is hard before it is easy. --Goethe',
    'Act as if what you do makes a difference. It does. --William James',
    'Even if you’re on the right track, you’ll get run over if you just sit there. --Will Rogers',
    'Never stop learning because life never stops teaching. --Unknown',
    'The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. --Brian Herbert',
    'Strength does not come from winning. Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength. --Arnold Schwarzenegger',
    'Still, I rise. --Maya Angelou',
    'The best thing you can do is MASTER the chaos in you. You are not thrown into the fire, you ARE the fire. --Mama Indigo',
    'It’s okay to be a glowstick: Sometimes we have to break before we shine. --Jadah Sellner',
    'Do something today that your future self will thank you for. --Unknown',
    'The greatest weapon against stress is the ability to choose one thought over another. --William Jame',
    'The difference between who you are and who you want to be is what you do. --Unknown',
    'When I win and when I lose, I take ownership of it, because I really am in charge of what I do. --Nicki Minaj',
    'A winner is a dreamer who never gives up. --Nelson Mandela',
    'Don’t stop when you are tired. Stop when you are done. --Unknown',
    'Motivation may be what starts you off, but it’s habit that keeps you going back for more. --Miya Yamanouchi',
    'Am I good enough? Yes I am. --Michelle Obama',
    'Success isn’t about how your life looks to others. It’s about how it feels to you. We realized that being successful isn’t about being impressive, it’s about being inspired.That’s what it means to be true to yourself. --Michelle Obama',
    'You miss 100% of the shots you don’t take. –-Wayne Gretzky',
    'The best time to plant a tree was 20 years ago. The second best time is now.',
    'I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. -–Maya Angelou',
    'Whether you think you can or you think you can’t, you’re right. -–Henry Ford',
    'People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily. –-Zig Ziglar',
    'Life is not measured by the number of breaths we take, but by the moments that take our breath away. -–Maya Angelou',
    'If you want to lift yourself up, lift up someone else. –-Booker T. Washington',
    'Build your own dreams, or someone else will hire you to build theirs. -–Farrah Gray',
    'It does not matter how slowly you go as long as you do not stop. –-Confucius',
    `If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. –-Oprah Winfrey`,
    'You can’t use up creativity.  The more you use, the more you have. -–Maya Angelou',
    'If you do what you’ve always done, you’ll get what you’ve always gotten. –Tony Robbin',
    'Dreaming, after all, is a form of planning. –-Gloria Steinem',
    `It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live. –-Mae Jemison`,
    'Remember no one can make you feel inferior without your consent. –-Eleanor Roosevelt',
    'Life is what we make it, always has been, always will be. -–Grandma Moses',
    'The question isn’t who is going to let me; it’s who is going to stop me. –-Ayn Rand',
    'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. –-Henry Ford',
    'It’s not the years in your life that count. It’s the life in your years. -–Abraham Lincoln',
    'Nothing is impossible, the word itself says, “I’m possible!” –-Audrey Hepburn',
    'I do my best because I’m counting on you counting on me. --Maya Angelou',
    'Develop enough courage so that you can stand up for yourself and then stand up for somebody else. --Maya Angelou',
    'You alone are enough. You have nothing to prove to anybody. --Maya Angelou',
    'We may encounter many defeats but we must not be defeated. --Maya Angelou',
    'If I am not good to myself, how can I expect anyone else to be good to me? --Maya Angelou',
    'My work is to be honest. My work is to try to think clearly, then have the courage to make sure that what I say is the truth. --Maya Angelou',
    'Each of us has that right, that possibility, to invent ourselves daily. If a person does not invent herself, she will be invented. So, to be bodacious enough to invent ourselves is wise. --Maya Angelou',
    'Success is liking yourself, liking what you do, and liking how you do it. --Maya Angelou',
    'We need much less than we think we need. --Maya Angelou',
    'We all believe in you --from the world',
    'Trust yourself',
    'One important key to success is self-confidence. An important key to self-confidence is preparation. --Arthur Ashe',
    'Shyness has a strange element of narcissism, a belief that how we look, how we perform, is truly important to other people. --Andre Dubus',
    'Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure. It is our light, not our darkness that most frightens us. We ask ourselves, Who am I to be brilliant, gorgeous, talented, and fabulous? Actually, who are you not to be? --Marianne Williamson',
    'You are allowed to be both a masterpiece and a work in progress simultaneously. --Unknown',
    'Eat like you love yourself. Move like you love yourself. Speak like you love yourself. Act like your love yourself. Love yourself. --Unknown',
    'No one can make you feel inferior without your consent. --Eleanor Roosevelt',
    'You are enough'
  ]

  // generates a random number from phrasesArray
  const randomIndex = randomNumber(phrasesArray.length)

  const randomPhrase = phrasesArray[randomIndex]

  return randomPhrase
}
